### ISSUE TITLE
please share a EPUB or PDF for printing

### ISSUE THREAD

**Issue by GETandSELECT** [codership/documentation#100]
The generation of single page HTML was also not successful.
```
System Message: WARNING/2 (t)
latex exited with error [stderr] kpathsea: Running mktexfmt latex.fmt /bin/mktexfmt: line 395: /usr/share/texlive/texmf/texconfig/tcfmgr: No such file or directory fmtutil: config file `fmtutil.cnf’ not found. [stdout] This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013) restricted \write18 enabled. I can’t find the format file `latex.fmt’! 
```
![big](https://cloud.githubusercontent.com/assets/10598483/9086393/793b2804-3b84-11e5-9df1-9038320aabd8.png)

please share a download with PDF or EPUB for printing. Thanks.

**Comment by philip-galera** [comment]
What happens if you run "make html"  in the documentation directory? Does it work for you ?

**Comment by GETandSELECT** [comment]
I did a "make singlehtml". It worked 95% for the text but there are those errors (see screenshot). I wish to have a printable version.

**Comment by philip-galera** [comment]
Please provide your email address to philip . stoev [AT] galeracluster dot com  and I will send you the documentation as a single html.

**Comment by philip-galera** [comment]
```make latexpdf``` now works for the documentation, so closing this ticket.
