### ISSUE TITLE
show add aliyun.com  mirrors  at the page to download mariadb?

### ISSUE THREAD

**Issue by joostshao** [codership/documentation#102]
show add aliyun.com  mirrors  at the page to download mariadb?
wget http://mirrors.aliyun.com/mariadb/mariadb-galera-10.0.21/source/mariadb-galera-10.0.21.tar.gz

**Comment by philip-galera** [comment]
Hello, I am not sure how we can help. Please direct your request to mariadb.com.

Galera Cluster is not involved with any particular mirror.
