### ISSUE TITLE
Missing wsrep options from documentation

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#106]
wsrep_preordered
wsrep_slave_FK_checks 
wsrep_slave_UK_checks
wsrep_restart_slave

**Comment by shinguz** [comment]
not in docu
evs.delay_margin = PT1S
base_dir = /home/mysql/data/galera-5.6.23-25.10-a/

**Comment by shinguz** [comment]
| wsrep_gcomm_uuid             | 7e729708-605f-11e5-8ddd-8319a704b8c4 |

**Comment by kennethpjdyer** [comment]
Missing variables now in docs.
