### ISSUE TITLE
PDF formatting issues

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#108]
1. I had to change some less than or equal signs:

```
commit 950566d97e143eadbf88f83d1494ac17d97594b4
Author: Philip Stoev <philip.stoev@galeracluster.com>
Date:   Fri Sep 25 03:41:39 2015 -0700

    Use a simpler, two-character <= sign in source/recovery.rst to allow for creation of PDF documentation
```

Otherwise make latexpdf complained about unknown unicode characters.
1. Some tables in the PDF 

http://galeracluster.com/documentation-webpages/galera-documentation.pdf

extend beyond the right margin of the page.
1. There were various warnings during the PDF generation.

**Comment by philip-galera** [comment]
The header at the top of each page of the PDF file says "release" without specifying which release it is. I think we should remove it altogether or replace it with a date/timestamp of some sort.

**Comment by kirjaamo** [comment]
These seem to be corrected.
