### ISSUE TITLE
wsrep_desync not documented

### ISSUE THREAD

**Issue by temeo** [codership/documentation#11]
<a href="https://github.com/grypyrg"><img src="https://avatars.githubusercontent.com/u/1330700?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grypyrg](https://github.com/grypyrg)**
_Tuesday Jun 17, 2014 at 10:11 GMT_
_Originally opened as https://github.com/codership/galera/issues/62_

----

wsrep_desync is missing from http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html

**Comment by kennethpjdyer** [comment]
wsrep_desync now documented in mysqlwsrepoptions.
