### ISSUE TITLE
Document how to secure various types of SST

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#110]
I am attaching a slide from a presentation that has all the relevant options. Please get back to me if you have any questions.

**Comment by philip-galera** [comment]
![image](https://cloud.githubusercontent.com/assets/8738032/10201173/53155162-67b3-11e5-9efb-26304481ca56.png)

**Comment by philip-galera** [comment]
The correct section name to use for mysqldump is [client]

**Comment by kennethpjdyer** [comment]
Fixes now in draft.
