### ISSUE TITLE
Description of migration procedure is highly inadequate

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#111]
it is not factually inaccurate, but it has logical gaps and is generally confusing. A reader is not given a sense of what and why he is doing. And "MyISAM master" - even though technically we may be migrating from MyISAM tables - come on!

Link: http://galeracluster.com/documentation-webpages/migration.html

**Comment by ayurchen** [comment]
Philip, could you check the chapter, my conclusions, and prioritize this?

**Comment by kennethpjdyer** [comment]
Fixes in the draft branch.
