### ISSUE TITLE
Document Load Balancers

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#116]
For the Deployments chapter of the User Guide, develop a new subchapter on configuring load balancers to work with Galera Cluster.  The current documentation has one page that suggests it's possible to use a load balancer and another that show where in the server infrastructure they should use load balancers, but provides nothing on what they should use and how they should use it.  (Meaning readers have to go looking for generic MySQL guides and blogposts to figure it out.)

We should have a page on setting up each of the three listed in the docs, (HAProxy, Pen and GLB), as well as any others getting wide-scale adoption.

**Comment by kennethpjdyer** [comment]
Documents setting up HAProxy from Percona: https://www.percona.com/doc/percona-xtradb-cluster/5.5/howtos/haproxy.html

**Comment by kennethpjdyer** [comment]
Documents setting up PXC reference with HAProxy https://www.percona.com/doc/percona-xtradb-cluster/5.5/howtos/virt_sandbox.html

**Comment by kennethpjdyer** [comment]
Documents Galera Load Balancer at MariaDB: https://mariadb.com/kb/en/mariadb/galera-load-balancer/

**Comment by kirjaamo** [comment]
@byte Can we close this issue? Setting up the three listed balancers (HAProxy, Pen and GLB) is described, if I understood the pages correctly.
