### ISSUE TITLE
Document Galera on CoreOS

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#118]
Document installation and deployment procedures for using Galera Cluster on CoreOS.  This should include any information needed on using Galera Cluster on CoreOS.  Additions should be made to both Container Deployments subchapter as well as the forthcoming Multinode Deployments subchapter (#115) relating to running Galera within Rocket containers.

**Comment by byte** [comment]
I don't think this is relevant any longer -- @kirjaamo ? I am happy to close this

**Comment by kirjaamo** [comment]
Issue not relevant any more.
