### ISSUE TITLE
Document PC recovery feature

### ISSUE THREAD

**Issue by temeo** [codership/documentation#12]
<a href="https://github.com/temeo"><img src="https://avatars.githubusercontent.com/u/6009633?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [temeo](https://github.com/temeo)**
_Tuesday Jun 17, 2014 at 13:29 GMT_
_Originally opened as https://github.com/codership/galera/issues/65_

----

3.x branch has a new wsrep provider option ``pc.recovery`` (boolean). If the value for this parameter is set to ``true``, primary component state is stored to disk and recovered from there when node is started.

Primary component is recovered automatically when all of the nodes that were present in the last known primary component have established communication between each other.

This feature solves two use cases:

* Automatic recovery from full cluster crash (for example full data center power outage)
* Graceful full cluster restart without the need for bootstrapping new primary component explicitly

Known limitations:
* If the wsrep position differs between nodes during the recovery, full SST is required
* ...

**Comment by kennethpjdyer** [comment]
Documented in pcrecovery and galeraparameters.
