### ISSUE TITLE
Document wsrep_evs_repl_latency status variable

### ISSUE THREAD

**Issue by temeo** [codership/documentation#13]
<a href="https://github.com/temeo"><img src="https://avatars.githubusercontent.com/u/6009633?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [temeo](https://github.com/temeo)**
_Thursday Jun 19, 2014 at 13:25 GMT_
_Originally opened as https://github.com/codership/galera/issues/67_

----

Docoment new status variable ``wsrep_evs_repl_latency``. The variable tells group communication replication latency. The latency is measured from the time point when message is sent to the time point when message is delivered.

The status variable format is the following:
```
wsrep_evs_repl_latency       | 0.00243433/0.144022/0.591963/0.215824/13
```
Fields are min/average/max/standard deviation/sample size.

**Comment by kennethpjdyer** [comment]
wsrep_evs_repl_latecy documented on galerastatusvariables.
