### ISSUE TITLE
Document Galera Use Cases

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#130]
MariaDB Documentation includes a page on Galera Use Cases.  We should include a section or page that expands upon the material here.  For instance,
- For Deployments chapter, page on Standard Deployments (multi-master and master-slave).
- Disaster Recovery: Page on setting up nodes in separate data center to facilitate disaster recovery.

Requires particular focus on interaction between database and application layers, (which we don't have a lot on, right now).

https://mariadb.com/kb/en/mariadb/galera-use-cases/

**Comment by byte** [comment]
Not in the documentation, but this should probably also be in the docs...
https://galeracluster.com/products/#use-cases

**Comment by kirjaamo** [comment]
@byte Would it be ok to add the use cases to this page: https://galeracluster.com/doc-preview/html_docs_20210201-1718-master/kb/index.html

**Comment by byte** [comment]
> @byte Would it be ok to add the use cases to this page: https://galeracluster.com/doc-preview/html_docs_20210201-1718-master/kb/index.html

yes, seems sensible

**Comment by kirjaamo** [comment]
Implemented.
