### ISSUE TITLE
Improve wsrep_preordered documentation

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#131]
Alex has said the following:

```
Preordered events are not supposed to interfer with locally originated events (i.e. they should not update/indert the same table), because they are applied AFTER replication (this eliminates replication latency wait between events as opposed to first applying and then replicating, which limits slave processing rate to 1/(repl_latency)).
```

So basically:
- use wsrep_preordered to speed up the case where a Galera cluster is a slave to traditional MySQL async replication. This option causes incoming async replication events to be applied faster.

- do not use the option if, on the cluster, you are updating on the same table that is being updated by async replication

**Comment by philip-galera** [comment]
If there is a section on Galera and async replication, make sure the option is referenced there as well.

**Comment by kennethpjdyer** [comment]
Fixed during last web update.
