### ISSUE TITLE
Document new libs-compat package

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#132]
On Centos 6 or 7, when installing the mysql-wsrep package one may get an error like this:

```
Transaction Check Error:
  file /usr/share/mysql/czech/errmsg.sys from install of mysql-wsrep-server-5.6-5.6.23-25.10.el6.x86_64 conflicts with file from package mysql-libs-5.1.73-3.el6_5.x86_64
```

The fix is as follows:

For Centos 6:

For Galera 5.5:
```
sudo yum upgrade -y mysql-wsrep-libs-compat-5.5
```
For Galera 5.6:
```
sudo yum upgrade -y mysql-wsrep-libs-compat-5.6 
```

For Centos 7:
For Galera 5.5:
```
sudo yum upgrade -y mysql-wsrep-shared-5.5 -x mysql-wsrep-shared-5.6
```
For Galera 5.6:
```
sudo yum upgrade -y mysql-wsrep-shared-5.6
```

Also, the entire section ```Removing Postfix``` needs to be removed, as this is now no longer required.

**Comment by kennethpjdyer** [comment]
Fixed during last web update.
