### ISSUE TITLE
Documentation for wsrep_slave_threads is unclear

### ISSUE THREAD

**Issue by tanji** [codership/documentation#134]
Documentation says:

This parameter determines the number of threads the node uses when it applies slave write-sets. In defining this value, use a figure that is more than twice the number of CPU cores available and at most one quarter the number of writing client connections the other nodes have.

Wouldn't it be "no more than twice CPU cores" instead?

**Comment by ayurchen** [comment]
The number of slave threads turns to be a strangely controversial parameter given its overall innocence... Everybody wants an exact number.

Here's my take on this:
  - having LESS then 2 times the CPU cores can rarely be beneficial
  - having MORE than a quarter of total client connections can rarely be beneficial
  - plus/minus 50% will likely make little to no difference
  - from the resource utilisation perspective, I'd keep the number of slave threads at a lower end

**Comment by kirjaamo** [comment]
@byte Can we close this issue? wsrep_slave_threads has been deprecated.

**Comment by byte** [comment]
> @byte Can we close this issue? wsrep_slave_threads has been deprecated.

but we have wsrep_applier_threads

https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-applier-threads

and that is worht documenting similarly, no?

**Comment by kirjaamo** [comment]
@byte Those things are already included in https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-applier-threads
