### ISSUE TITLE
Expand cluster backup chapter

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#139]
Kenneth, 

Could you kindly expand the 
http://galeracluster.com/documentation-webpages/backingupthecluster.html
chapter using my reply on the mailing list below. Specifically I mean a command-line example and some explanation that one can either use SST scripts, but they are limited, or write his own script.

On 2015-12-16 18:27, Damien Dye wrote:

>    Hi guys am looking at getting garb to take backups of the cluster in a  controlled way for the purposes of external backup.
> 
>    http://galeracluster.com/documentation-webpages/backingupthecluster.html
> 
>    says I should be to pass --sst backup to garb and it work.
> 
>    my cluster is using xtrabackup-v2  how would I get this to work so that the cluster data ends up on the garb node ?

SST scripts that come with the distribution are designed to provision a new node. You'll need to modify one of them according to your particular backup needs.

One option is to start the original SST script manually in "joiner" mode (see how joining node does it in the error log) on a machine where you want to have a backup, it will open a socket listening for connection from "donor" - and then pass the address of this socket on a garbd command line. For example:

On backup machine:

```
$ wsrep_sst_rsync --role 'joiner' --address '10.21.32.1:3333' --datadir '/tmp/backup/' --defaults-file '' --defaults-group-suffix '' --parent $$
```

Note the output:

```
ready 10.21.32.1:3333/rsync_sst
```

Anywhere:

```
$ garbd --address gcomm://10.21.32.1:4567?gmcast.listen_addr=tcp://0.0.0.0:4560  --group my_cluster --sst rsync:10.21.32.1:3333/rsync_sst
```

Note1: gmcast.listen_addr=tcp://0.0.0.0:4560 is specified to allow garbd to run on any machine, including a node, so default listen port is changed to avoid collision.

Note2: value of the --sst option is `<sst_method>:<sst_address>`, where `<sst_address>` is given in the output of the joiner script above.

Xtrabackup is more complicated, you may need to forge my.cnf for it.

Or simply start another node, let is join the cluster and shut it down gracefully. There - you have a backup!

**Comment by kirjaamo** [comment]
@byte  I think we have cluster backup described well enough: https://galeracluster.com/library/documentation/backup-cluster.html. Do you agree?

**Comment by byte** [comment]
> @byte I think we have cluster backup described well enough: https://galeracluster.com/library/documentation/backup-cluster.html. Do you agree?

nope. everything alexey asked for is still not around.

we need to also cover xtrabackup, mariabackup.
