### ISSUE TITLE
[Documentation] Automatic donor selection in 3.6

### ISSUE THREAD

**Issue by temeo** [codership/documentation#14]
<a href="https://github.com/ronin13"><img src="https://avatars.githubusercontent.com/u/271234?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ronin13](https://github.com/ronin13)**
_Thursday Jul 03, 2014 at 15:42 GMT_
_Originally opened as https://github.com/codership/galera/issues/75_

----

The automatic donor selection in 3.6 based on gcache seqno limits and IST/SST accordingly is not documented.

**Comment by kennethpjdyer** [comment]
Documented in nodeprovisioning.
