### ISSUE TITLE
Implement Docs Build Testing

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#141]
Related to #108.  Implement build tests for HTML and PDF as well as some form of style checker to be run on the docs before web updates, to ensure that nothing gets added that puts the PDF out of alignment.

**Comment by philip-galera** [comment]
What kind of tests / style checker you would like to see?

**Comment by kennethpjdyer** [comment]
Sphinx doesn't handle errors and warnings very well on PDF builds, mainly because it calls pdflatex at `finish()` to go from the intermediary file galera.tex to the final PDF.  When we get errors there they're LaTeX errors, which are coughed out with a few pages of stdout messages and no real indication of the what or why, except for a line number in the galera.tex file.  

We need a style checker that can cite specific problems in the offending RST file, which'll make fixing the PDF builds much more manageable.  And, preferably something we can extend down the road, (like, keeping reference pages alphabetized or reducing our use of external resources).

On the OpenStack HA Guide, they handle this with tox, using doc8 for style-checking.  Going to test it out this weekend to see if it helps any with PDF output.  If not I'll do some research into alternatives.

**Comment by byte** [comment]
Do we really need this to still remain open @kirjaamo ?

**Comment by kirjaamo** [comment]
Not from my perspective, anyway. We do not produce PDF so often and if the HTML build is successful, I guess the PDF will be, too.
