### ISSUE TITLE
4.x: Document Non-Blocking DDL

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#142]
This ticket will contain the information about non-blocking DDL that should be put into a separate branch of the documentation tree.

**Comment by philip-galera** [comment]
# The Problem

Under the TOI method for replicating DDL, practically all updates in the cluster are blocked while a long-running DDL is in progress.

# The Solution

A new setting for ```wsrep_osu_method``` - ```NBO``` is introduced. It operates in the following manner:

1. At the start of the DDL, table locks (also known as metadata locks) are taken on all nodes in order to ensure that the DDL operation will be consistent on all nods
2. The DDL operation is executed on all nodes, using a separate applier thread
3. The table locks are released on all nodes simultaneously 


# Usage

```
SET SESSION wsrep_OSU_method='NBO';
ALTER TABLE table_name LOCK = {SHARED|EXCLUSIVE} , alter_specification
```

# Supported DDL statements

* ```ALTER TABLE table_name LOCK = {SHARED|EXCLUSIVE} , alter_specification```
* ```ANALYZE TABLE```
* ```OPTIMIZE TABLE```



# Unsupported DDL statements

If an attempt is made to run an unsupported DDL while NBO is in effect, the following error will be returned:

```
ERROR 42000: wsrep_OSU_method NBO not supported for query
```

Unsupported statements are:

* ```ALTER TABLE LOCK = {DEFAULT|NONE}``` is not supported.
* This also means that ```ALTER TABLE``` without a ```LOCK``` clause is not supported, as is defaults to ```DEFAULT```.
* CREATE, RENAME, DROP, REPAIR

# Limitations

* Since running DDL statements such as CREATE and simple ALTER without a LOCK argument will return an error if run under NBO, it is not recommended to set wsrep_OSU_method to NBO on a server-wide basis. Instead, set wsrep_OSU_method to NBO only for the specific sessions that run DDL statements compatible with NBO.
* It is not possible to perform writes on a table that is being altered under NBO. Write attempts will block until the ALTER is complete. Under LOCK=SHARED, reading from the table is allowed. Under LOCK=EXCLUSIVE, read operations will also be blocked.
* Acquiring the table locks in the beginning of the operation is still a blocking operation. The cluster may block if there is an ongoing long transaction against the table being altered. To avoid this, ensure that no clients have open transactions that include the table prior to running the ALTER statement.
* While a DDL operation is in progress, nodes can not be donors for SST. This means that if a node will be unable to join or rejoin the cluster using SST while a NBO DDL is in progress. If a node leaves the cluster while a NBO DDL operation is in progress, it can only rejoin the cluster via IST and not SST;
* Therefore, if a DDL statement is expected to take 1 hour, this creates a 1-hour window during which SST will not be available, only IST. The gcache.size value should be set high enough accordingly so that there is sufficient cached data to perform IST.

**Comment by kennethpjdyer** [comment]
Docs for this feature are now in 4.x-draft and ready for reviews.

**Comment by philip-galera** [comment]
Merged.
