### ISSUE TITLE
4.x: Document Streaming Replication

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#143]
# Overview

Traditionally in Galera Cluster, all replication and certification happen at transaction commit time.

With Streaming Replication, fragments of the transaction are certified, replicated and applied on the slaves while the transaction is in progress. Once certified, a fragment can no longer be aborted by a conflicting transaction.

Streaming Replication also transactions with a write set larger than 2Gb to be processed by Galera.

# Use cases

## Long-running Write Transactions

Without streaming replication, Long-running write transactions in Galera Cluster have a higher chance of aborting due to the increased time window during which a smaller, conflicting transaction will be executed on another node, causing the longer transaction to abort. Furthermore, while a long-running transaction is being applied on the slaves, they can not commit any other transactions, which may result in flow control throttling of the entire cluster.

With streaming replication, once a fragment of the transaction has been replicated and certified, it can no longer be aborted by other transactions. This substantially increases the probability that the entire long transaction will be able to run to completion on the master.

After a slave has applied a particular fragment, it can apply and commit other concurrent transactions without blocking, This way the entire transaction can be processed on the slaves with minimal impact on the other transactions.

## Hot Records

If the application frequently updates one and the same records from the same tables, such as when implementing a locking scheme, counters, job queues or similar, you can perform this update in the beginning of your transaction and use Streaming Replication to force it to be replicated to the entire cluster. This will effectively cause the hot records to become locked on all nodes, and other transactions will be prevented from modifying them. This increases the chance that the entire transaction will be able to commit successfully and the client will get the desired outcome, such as being given a place in the queue. An example of such a transaction would be:

```
START TRANSACTION;
# Read data
SELECT ...
SELECT ...

# Update the hot record
SET SESSION wsrep_trx_fragment_unit='statement';
SET SESSION wsrep_trx_fragment_size=1;
UPDATE hot_table SET counter = counter + 1;
SET SESSION wsrep_trx_fragment_size=0;

# Perform further work within the transaction
SELECT ...
UPDATE ...
DELETE ...

# Complete the transaction
COMMIT;
```

## Transactions Writing Large Volumes of Data

When Streaming Replication is enabled, data will begin to be replicated while the transaction is still in progress. This can benefit transactions inserting or updating large volumes of data over slower network links by spreading the replication traffic over the lifetime of the transaction rather than attempting to push it all through at commit time.

# Configuration options

- wsrep_trx_fragment_size=N

A new fragment will be generated every time the transaction accumulates N replication units. The default is zero meaning no streaming replication will take place.

- wsrep_trx_fragment_unit

Specifies the units that will be counted in order to determine if it is time to replicate another fragment. Possible values are bytes, events, rows, statements  . Default is 'bytes'.

events refers to binary log events generated by the transaction. rows refers to the number of rows updated.

# Please note:

- In order to ensure persistence of Streaming Transactions in case of node crashes, the write sets from each transaction fragment are recorded in a dedicated table ```wsrep_schema.SR``` on all nodes. Writing to this table increases the load on the nodes so you should not use Streaming Replication for transactions that are running correctly without it.
- It is recommended to set the wsrep_trx_fragment_size variable on a per-session basis and only for transactions where it is needed.
- If a long-running transaction needs to be rolled back for whatever reason, the rollback operation will consume system resources on all nodes. It is good application design to use shorter transactions whenever possible.
- If your application performs batch processing or scheduled housekeeping tasks, you can consider splitting those tasks into smaller transactions in addition to using Streaming Replication.

**Comment by kennethpjdyer** [comment]
Docs now in 4.x-staging.
