### ISSUE TITLE
4.x What's New Page (was re: Changelog)

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#146]
Create a page in the Reference or Troubleshooting chapters that lists changes introduced in new versions of Galera.  Something along the lines of What's New in 4.x, listing general new features and parameters added.  

Make the page generic, so that we can expand it with future releases.

**Comment by philip-galera** [comment]
Let's call it "What is New" rather than changelog.

**Comment by ayurchen** [comment]
Well, if it is supposed to list all historical changes - and that's useful - then "Changelog" or "Changes" is better.

**Comment by philip-galera** [comment]
We are not currently set up to track all changes in a repeatable and exhaustive manner the way Oracle does it for MySQL. Maybe at some later time we can have that. So let's try with a "What's new" page first.

**Comment by philip-galera** [comment]
Merged.
