### ISSUE TITLE
3.x: Document wsrep_dirty_reads

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#149]
Document new variable wsrep_dirty_reads

Original documentation, just for reference is here:

https://www.percona.com/doc/percona-xtradb-cluster/5.6/wsrep-system-index.html#wsrep_dirty_reads

Scope: session
Default: OFF

When set to on, it is possible to access the data on a a node that is in a non-primary state.

The following statements are allowed:
* SELECT
* LOCK TABLE and UNLOCK TABLE

The following statement are not allowed:
* DDL
* DML statements such as INSERT, DELETE , UPDATE

The wsrep_sync_wait must be set to 0 otherwise a deadlock error will be returned even if wsrep_dirty_reads is set to ON. The data read from a non-primary server using this option may be stale.

**Comment by kennethpjdyer** [comment]
Added in last update.
