### ISSUE TITLE
3.x: Document wsrep_reject_queries

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#150]
A new variable is available wsrep_reject_queries, which causes the node to begin rejecting all client queries while continuing to perform replication and participate in the cluster in all other ways.

The option may be useful in certain maintenance situations. Note that all queries will be rejected, including SELECTs.

Scope: GLOBAL
Default: NONE

Values:

NONE - does not reject any queries
ALL - rejects all queries with ER_UNKNOWN_COM_ERROR (code 1047) error
ALL_KILL - rejects all queries and in addition terminates all client connections including the one that issued the SET GLOBAL.

Original documentation:

https://www.percona.com/doc/percona-xtradb-cluster/5.6/wsrep-system-index.html#wsrep_reject_queries

**Comment by kennethpjdyer** [comment]
Added in last update.
