### ISSUE TITLE
Fix Index Directive Calls

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#157]
When looking at the index on the PDF, noticed several instances where the index entries were not rendering correctly.  This appears to stem from typos in the index directive calls.  For instance, there's an entry for 'pairs'.  Pairs is actually an option for the index directive, it shouldn't appear in the output.  Elsewhere, evs.evict matches to ": Parameters" rather than "Parameters."

**Comment by philip-galera** [comment]
Merged.
