### ISSUE TITLE
Document gvwstate.dat

### ISSUE THREAD

**Issue by temeo** [codership/documentation#16]
<a href="https://github.com/ronin13"><img src="https://avatars.githubusercontent.com/u/271234?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ronin13](https://github.com/ronin13)**
_Friday Jul 25, 2014 at 10:56 GMT_
_Originally opened as https://github.com/codership/galera/issues/84_

----

Purpose and (internal) use of this file is not documented.

**Comment by kennethpjdyer** [comment]
Documented in pcrecovery and galeraparameters.
