### ISSUE TITLE
Adjust CSS for Glossary Term Links

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#169]
When Sphinx processes glossary terms, it writes in extra classes to distinguish them from normal :ref: objects in the output.  Add a few lines of CSS to adjust the color or appearance of glossary terms to reduce tendency of multiple links in a paragraph from obstructing readability.

**Comment by kirjaamo** [comment]
@byte Which color would you like to have?

**Comment by kirjaamo** [comment]
@byte This is what it looks like. I'lll make a pull requestr.

![image](https://user-images.githubusercontent.com/23026377/107019520-6fa33400-67aa-11eb-99f7-e81ffcaced3d.png)

**Comment by kirjaamo** [comment]
Yes, this looks good to me.

**Comment by kirjaamo** [comment]
Fixed on master.
