### ISSUE TITLE
Incorrect documentation for rpm installation

### ISSUE THREAD

**Issue by temeo** [codership/documentation#17]
<a href="https://github.com/zba"><img src="https://avatars.githubusercontent.com/u/807956?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zba](https://github.com/zba)**
_Monday Jul 28, 2014 at 04:14 GMT_
_Originally opened as https://github.com/codership/galera/issues/87_

----

I tryed with centos6 , followed [this](http://galeracluster.com/documentation-webpages/installmysqlrpm.html)

Centos6 has no mysql-client package, also if I try to install mysql-community-client from oracle repository it tells about conflicts, do you provide actual documentation for rhel6/centos6 ? 

also what means strings like this ?

-----

`3.` Install the compatibility libraries:

    rpm -e mysql-shared-compat.rpm

-----

doesn't it should be like

      rpm -i mysql-shared-compat-*.rpm 

or something like this ?

**Comment by kennethpjdyer** [comment]
Fixed.
