### ISSUE TITLE
Expand Migration Chapter

### ISSUE THREAD

**Issue by kennethpjdyer** [codership/documentation#173]
Right now, migration chapter has two main sections: one on the differences between Galera and MySQL, another on updating system tables and migrating from MySQL to Galera.  We should expand this with new material covering migration from other databases (PostgreSQL, MongoDB, et cetera), as well as an update for enabling Galera Cluster for MariaDB 10.1+.

**Comment by kirjaamo** [comment]
@byte Is this ticket still valid?
