### ISSUE TITLE
GRA files in data dir - DBA actions/taks? 

### ISSUE THREAD

**Issue by GETandSELECT** [codership/documentation#181]
see https://github.com/codership/documentation/issues/98

one important topic is missing. What's is the DBA action/task when there are thousands of GRA files?
please update the documentation with more details.

Does the application receive error message if there is a replication failure? How is the message?

**Comment by kirjaamo** [comment]
@philip-galera Does the new section _Utility Scripts_ address this request?

**Comment by byte** [comment]
Nothing to do with utility scripts, but the GRA stuff is sorted by https://github.com/codership/documentation/pull/447/

however, what does the DBA have to do, or an action, is up to the DBA. Application does not receive a message.
