### ISSUE TITLE
systemd start incorrect on page startingcluster.html

### ISSUE THREAD

**Issue by grooverdan** [codership/documentation#187]
On page http://galeracluster.com/documentation-webpages/startingcluster.html

<pre>
 systemctl start mysql --wsrep-new-cluster
</pre>

Is specified. systemctl will never pass a second option though to a way that a mysql.service can see. As such MariaDB did it this way:

https://github.com/MariaDB/server/blob/10.2/scripts/galera_new_cluster.sh is the mariadb way (running galera_new_cluster (no .sh))

Percona is https://www.percona.com/doc/percona-xtradb-cluster/5.7/manual/bootstrap.html (./scripts/galera_new_cluster.sh) (systemctl start mysql@bootstrap.service).

**Comment by grooverdan** [comment]
still broken and wrong.

**Comment by kirjaamo** [comment]
@byte Can I fix this isse by adding:

Starting in Percona XDC version 5.7, which includes Galera version 4, you can enter instead the following from the command-line to start XDC, Galera, and to establish the Primary Component:
`galera_new_cluster_sh`

Should:
`systemctl start mysql --wsrep-new-cluster`
be replaced with
`service start mysql --wsrep-new-cluster`

**Comment by byte** [comment]
@kirjaamo percona does it: systemctl start mysql@bootstrap.service

see: https://www.percona.com/doc/percona-xtradb-cluster/8.0/bootstrap.html

For galera, we do it: mysqld_bootstrap --wsrep-new-cluster

and @grooverdan is correct about the mariadb variant

**Comment by kirjaamo** [comment]
@byte Can you check that I got it right?

**Comment by kirjaamo** [comment]
Fixed and merged to master.

**Comment by grooverdan** [comment]
Thanks for your efforts @byte
