### ISSUE TITLE
gcache.mem_size should be deprecated

### ISSUE THREAD

**Issue by temeo** [codership/documentation#19]
<a href="https://github.com/temeo"><img src="https://avatars.githubusercontent.com/u/6009633?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [temeo](https://github.com/temeo)**
_Tuesday Sep 09, 2014 at 07:50 GMT_
_Originally opened as https://github.com/codership/galera/issues/114_

----

As discussed here:
https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1359700

gcache.mem_size is not supported and causes crashes. Either it should be removed from the allowed configuration options and documentation or the crashes should be fixed.

**Comment by kennethpjdyer** [comment]
Fixed.
