### ISSUE TITLE
Anchor for options and variables is IMHO at wrong place

### ISSUE THREAD

**Issue by shinguz** [codership/documentation#190]
When documentation is studied for options and variables:

http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html
http://galeracluster.com/documentation-webpages/galeraparameters.html
http://galeracluster.com/documentation-webpages/galerastatusvariables.html

And one clicks on a TOC item it jumps to the text straight under the title and not to the text title:

<p class="rubric"><tt class="docutils literal"><span class="pre">wsrep_cluster_name</span></tt></p>
<span class="target" id="wsrep-cluster-name"></span><p id="index-7">Defines the logical cluster name for the node.</p>

Span class pre and span class target should be swapped or so...

This is nasty...

**Comment by shinguz** [comment]
Such lines need to me swapped IMHO:

.. rubric:: ``wsrep_data_home_dir``
.. _`wsrep_data_home_dir`:

But want to have confirmation of Philip first! Its a lot of boring work...

**Comment by kirjaamo** [comment]
This has already been fixed.
