### ISSUE TITLE
wsrep_recover option is missing under variables

### ISSUE THREAD

**Issue by shinguz** [codership/documentation#192]
http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html

wsrep_recover option is missing under variables

**Comment by kirjaamo** [comment]
Can I copy/paste the content from here: https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_recover

**Comment by kirjaamo** [comment]
@byte Or should this be part of MariaDB Server Options?

**Comment by byte** [comment]
@kirjaamo I have no idea how this is also missing from documentation, but wsrep_recover is documented on our site:
* https://galeracluster.com/library/training/tutorials/restarting-cluster.html
* https://galeracluster.com/2016/11/introducing-the-safe-to-bootstrap-feature-in-galera-cluster/

It is just missing but present

The link you found here, is ok https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_recover
(and ironically, also documented here https://www.percona.com/doc/percona-xtradb-cluster/LATEST/howtos/crash-recovery.html )

Yes, please gain inspiration and provide the appropriate credit, in your pull request

**Comment by kirjaamo** [comment]
Fixed in master.
