### ISSUE TITLE
Clean up Symptoms and Solutions

### ISSUE THREAD

**Issue by temeo** [codership/documentation#2]
<a href="https://github.com/kennethpjdyer"><img src="https://avatars.githubusercontent.com/u/6652799?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kennethpjdyer](https://github.com/kennethpjdyer)**
_Friday Apr 25, 2014 at 21:45 GMT_
_Originally opened as https://github.com/codership/galera/issues/4_

----

At the moment, symptomsolution.rst renders as a table where the particular symptom is listed in the left column and a very detailed solution is listed in the right column.  While the logic of this is pretty clear, on a webpage the table formatting makes it difficult to read and find what you're looking for.  Additionally, the table entries do not posses id references, so, in the event of a client having difficulties, it's not possible to link them to a particular symptom / solution pairing on the page.

Rewrite the table material into separate sections.  If there are enough entries to justify it, set up a link table like on the parameters pages.

**Comment by kennethpjdyer** [comment]
Done.
