### ISSUE TITLE
Cluster restarting improvement required

### ISSUE THREAD

**Issue by renich** [codership/documentation#206]
Hello,

I think this document requires improvement: http://galeracluster.com/documentation-webpages/restartingcluster.html

The grastate.dat file is not well explained. Also, there is kind of a misconception of what seqno is supposed to show. For example, while a node is running. seqno will be -1. It is until the node stops that seqno is set to some integer.

**Comment by kirjaamo** [comment]
The link is obsolete, here's a new one: 
https://galeracluster.com/doc-preview/html_docs_20210203-1048-master/training/tutorials/restarting-cluster.html?highlight=restarting

Questions:

- How should the grastate.dat file look like in each example? 
- What exactly is the misconception about the seqno? In section "Identifying Crashed Nodes" the seqno is -1, in other examples, it is an integer.

**Comment by byte** [comment]
@kirjaamo both links are obsolete for some reason. Please see:
https://galeracluster.com/library/training/tutorials/restarting-cluster.html

Again, I would take some inspiration from https://www.percona.com/doc/percona-xtradb-cluster/LATEST/howtos/crash-recovery.html and also see if we can further clearly explain everything asked here: https://forums.percona.com/t/explanation-of-the-entries-in-grastate-dat-file/4080

I also want to note that we have a real world example here:
https://mariadb.com/kb/en/local-state-seqno-out-of-sync-with-group/

And... I wonder where we end up talking about this: https://mariadb.com/kb/en/manual-sst-of-galera-cluster-node-with-percona-xtrabackup/ and https://mariadb.com/kb/en/manual-sst-of-galera-cluster-node-with-mariabackup/

**Comment by kirjaamo** [comment]
Fixed in master.
