### ISSUE TITLE
[sst] cpat documentation issues

### ISSUE THREAD

**Issue by hholzgra** [codership/documentation#227]
Documentation for the wsrep_sst_mariabackup `[sst] cpat` parameter says 

> Defines what files to clean up from the datadir during state transfers.

But actually it defines what files to exclude from delete, so the opposite of what the documentation says.

Also its default value is given as empty string, while actually it's set to

`'.*\.pem$\|.*init\.ok$\|.*galera\.cache$\|.*sst_in_progress$\|.*\.sst$\|.*gvwstate\.dat$\|.*grastate\.dat$\|.*\.err$\|.*\.log$\|.*RPM_UPGRADE_MARKER$\|.*RPM_UPGRADE_HISTORY$'`

by default in wsrep_sst_xtrabackup_v2

**Comment by kirjaamo** [comment]
@byte Can I fix this in documentation?

**Comment by byte** [comment]
> @byte Can I fix this in documentation?

Yes, except, dare I ask, where is wsrep_sst_mariabackup even documented, @kirjaamo ? We currently don't document this (yes, some of these scripts are shipped, but definitely missing from the documentation)

**Comment by kirjaamo** [comment]
@byte Can I add the mariabackup option here: https://galeracluster.com/documentation/html_docs_20210310-0827-mariadb-options/documentation/mysql-wsrep-options.html#wsrep-sst-method?

And state that "The mariabackup SST method uses the Mariabackup utility for performing SSTs. It does not block the donor node."

And add a link: https://mariadb.com/kb/en/mariabackup-sst-method/

Or should this be part of _MariaDB Options_ page?

**Comment by kirjaamo** [comment]
@byte Is mariabackup deprecated? See list in https://github.com/codership/documentation/issues/388. If yes, can we close this issue?

**Comment by byte** [comment]
> @byte Is mariabackup deprecated? See list in #388. If yes, can we close this issue?

mariabackup is what you find in MariaDB Server not Galera Cluster (MySQL based). 

wsrep_sst_common
wsrep_sst_mariabackup
wsrep_sst_mysqldump
wsrep_sst_rsync
wsrep_sst_rsync_wan
