### ISSUE TITLE
Better document function WSREP_SYNC_WAIT_UPTO_GTID()

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#230]
The documentation for function `WSREP_SYNC_WAIT_UPTO_GTID()` (https://galeracluster.com/library/documentation/wsrep-functions.html#wsrep-sync-wait-upto-gtid) needs improvements.
The following issues should be addressed:
* The table lists `Function` name as `WSREP_LAST_WRITTEN_GTID()`. This should be corrected, the table should say `WSREP_SYNC_WAIT_UPTO_GTID()`
* Optional argument `timeout` is not documented. Are these seconds? minutes? hours?
* The documentation should clarify what is the default timeout. Currently it says that the default timeout is `repl.causal_read_timeout`. I'm not sure this is the case anymore.
* An example using the optional timeout parameter would be beneficial

**Comment by mkaruza** [comment]
Done with commit fed71deb8c62242c73e5e71f170b9f1db446d80b
