### ISSUE TITLE
Change copyright to 2021

### ISSUE THREAD

**Issue by byte** [codership/documentation#239]
Today it says: 2014 Codership Ltd.

Please make sure it says 2021

**Comment by byte** [comment]
https://github.com/codership/documentation/blob/master/galeracluster/source/_templates/layout.html

**Comment by kirjaamo** [comment]
Change year in rst files 2014-2020 -> 2014-2021

**Comment by kirjaamo** [comment]
Did you merge or shall I do it?

**Comment by kirjaamo** [comment]
How can I link a pull request to an issue? To the right, the **Linked pull requests** does not contain my pull request even though I mentioned this issue in the push.

**Comment by kirjaamo** [comment]
I did a merge, but I cannot push master.

**Comment by kirjaamo** [comment]
Copyrights changed and pushed.
