### ISSUE TITLE
Image still shows incorrect ports 9091-9092

### ISSUE THREAD

**Issue by byte** [codership/documentation#242]
Needs to change to 8081-8082 not 9091-9092

Do we really need "Along these lines, you might also change ports 9100 - 9104 to the IP address of wherever Galera Manager or gmd is running."

https://galeracluster.com/library/documentation/galera-manager-ports.html

**Comment by kirjaamo** [comment]
Can you take a new screenshot and see if we can remove the sentence "Along these...".

**Comment by byte** [comment]
I'll take the image and also commit to the tree, thanks @kirjaamo

**Comment by kirjaamo** [comment]
Can we close this issue?

**Comment by byte** [comment]
yes, we close this, considering things are... changed now anyway
we need to change Galera Manager docs
