### ISSUE TITLE
Document Percona XtraDB Cluster Options

### ISSUE THREAD

**Issue by kirjaamo** [codership/documentation#262]

**Comment by kirjaamo** [comment]
Add at least wsrep_replicate_myisam:

-  https://www.percona.com/doc/percona-xtradb-cluster/LATEST/wsrep-system-index.html

**Comment by byte** [comment]
gcache.freeze_purge_at_seqno is not documented, see https://www.percona.com/doc/percona-xtradb-cluster/LATEST/wsrep-provider-index.html and also a blog post to show it https://www.percona.com/blog/2018/02/13/no-sst-node-rejoins/

**Comment by byte** [comment]
wsrep_ist_receive_status https://www.percona.com/doc/percona-xtradb-cluster/LATEST/wsrep-status-index.html

**Comment by kirjaamo** [comment]
@byte, wsrep_last_applied is referred to in the gcache.freeze_purge_at_seqno. Maybe we should add that, too, to Galera Status Variables. What do you think?
