### ISSUE TITLE
Document EVS auto eviction

### ISSUE THREAD

**Issue by temeo** [codership/documentation#27]
Overwiew:
--------------

Auto eviction is a process to remove a node with erratic behavior permanently from cluster.

Each of the nodes monitor group communication response times from other nodes and if one of the other nodes gets delayed for more than `evs.delay_margin` from expected response time, it will be added to the list of delayed nodes. If node on delayed list stays responsive for `evs.delayed_keep_period` time, one entry is removed from delayed list. If the number of entries in delayed list for some node reaches `evs.auto_evict` and majority of the nodes have it on delayed list, the node is evicted permanetly from the cluster and cannot join back until restarted.

Related Parameters:
----------------------------
evs.delay_margin:

Time period that a node can delay its response from expected until it is added to delayed list. The value must be higher than the highest RTT between nodes. Default PT1S.

evs.delayed_keep_period:

Time period that node is required to remain responsive until one entry is removed from delayed list. Default PT30S.

evs.evict

Manual eviction can be triggered by setting evs.evict to certain node value. Setting evs.evict to empty string will clear the evict list on the node where it is set.

evs.auto_evict:

Number of entries allowed on delayed list until auto eviction takes place. Setting value to 0 disables auto eviction protocol on the node, though node response times will still be monitored. Default 0.

evs.version:

EVS protoco version. Auto eviction is enabled on evs.version=1. Default 0 for backwards compatibility.

New Status Variables:
-----------------------------

The following status variables have been added:

wsrep_evs_state:

Internal EVS protocol state.

wsrep_evs_delayed:

Comma separated list of nodes that are considered delayed. The node format is `<uuid>:<address>:<count>` where `<count>` is the number of entries on delayed list for that node.

wsrep_evs_evict_list:

List of UUIDs of the evicted nodes.

Upgrade From Previous Versions:
----------------------------------------------

In order to take advantage of auto eviction, EVS protocol must be upgraded to version 1.

Versions before 3.8 used evs.version=0 and are not directly compatible with evs.version=1. Upgrade from previous versions must be in the following way:

* Start upgraded node with evs.version=0 in wsrep_provider_options
* Once all nodes have been upgraded, set evs.version=1 in
  wsrep_provider_options on all of the nodes.
* Add evs.version=1 to wsrep_provider_options in configuration to make
  sure that version upgrade is maintained in the following restarts.

**Comment by kennethpjdyer** [comment]
Almost done the page for this, question for the reference entries though:

For the evs.* options:  I see evs.version is in there already, were the rest introduced for Galera 3.8?  Are any of them dynamic?  Is there a default value for evs.evict?

For the status variables: Are they also introduced in Galera 3.8?  Do we have example value for them?

**Comment by kennethpjdyer** [comment]
Done.
