### ISSUE TITLE
Document Percona LDAP usage

### ISSUE THREAD

**Issue by byte** [codership/documentation#270]
Present in 8.0.23

**Comment by kirjaamo** [comment]
Can I get the info from here?

https://www.percona.com/doc/percona-server/8.0/security/simple-ldap.html

**Comment by byte** [comment]
Yes, but attribution is important

**Comment by kirjaamo** [comment]
Yes, attribution is important. Ahould I write that "This feature and documentation are adapted from Percona MySQL Server" or "This feature and documentation are adapted from MySQL Enterprise Simple LDAP plugin"?

**Comment by byte** [comment]
Hi @kirjaamo 

Following https://github.com/percona/percona-server/blob/8.0/doc/source/copyright.rst and https://creativecommons.org/licenses/by-sa/2.0/

Thank you

Submit a pull request when done, I will test after reading
