### ISSUE TITLE
Relation between gcs.fc_master_slave and gcs.fc_limit is missing

### ISSUE THREAD

**Issue by shinguz** [codership/documentation#279]
Relation between gcs.fc_master_slave and gcs.fc_limit some how got lost when you changed from old to new docu:

https://web.archive.org/web/20131220184116/www.codership.com/wiki/doku.php?id=flow_control&s[]=fc

gcs.fc_master_slave specifies whether there are more than 1 source of replication. When it is set to NO (multi-master) gcs.fc_limit is modified by the square root of the cluster size (that is in 4-node cluster it is two times higher than the base value). This is done to compensate for the increasing replication rate noise. Default: NO.

**Comment by kirjaamo** [comment]
Can I fix this by replacing:
Defines whether there is only one master node in the group.
->
Defines whether there are more than one source of replication. When this parameter value is set to NO (multi-master) , the _gcs.fc_limit_ parameter is automatically modified by the square root of the cluster size, that is, in four-node cluster it is two times higher than the base value. This is done to compensate for the increasing replication rate noise.
