### ISSUE TITLE
Mention the possibility to install galera on freebsd with packages

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#286]
The section "Installing Galera Cluster" in this documentation page https://galeracluster.com/library/documentation/jails.html#using-jails states the following:

```
Regardless of whether you are on the host system or working from within a jail, currently, there is no binary package or port available to fully install Galera Cluster on FreeBSD. You must build the database server from source code.
```

However, we do have packages available, and it should perhaps be stated here.

**Comment by kirjaamo** [comment]
Would it be ok to say:

Regardless of whether you are on the host system or working from within a jail, you can install Galera Cluster on FreeBSD from a binary package, or build the database server from source code.

**Comment by byte** [comment]
@kirjaamo sure, create a PR to this effect

**Comment by byte** [comment]
i merged this fix
