### ISSUE TITLE
apparmor and debian documentation 

### ISSUE THREAD

**Issue by byte** [codership/documentation#287]
There are instructions to disable apparmor on distros derived from Debian in https://galeracluster.com/library/training/tutorials/galera-installation.html#disabling-apparmor, but nothing in https://galeracluster.com/library/documentation/install-mysql.html

Shouldn't the installation page also document disabling apparmor?

**Comment by kirjaamo** [comment]
@byte Can I use the same text in installing MySQL as is used in Debian installation?

**Comment by byte** [comment]
> @byte Can I use the same text in installing MySQL as is used in Debian installation?
 sure but we need to ensure that it exists in the main install doc
