### ISSUE TITLE
Options wsrep_trx_fragment_unit does not take value 'events'

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#303]
The documentation states that wsrep_trx_fragment_unit can be set to value 'events':
https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-trx-fragment-unit

I believe that's not the case, and if so, that bit should be removed from the documentation.

**Comment by kirjaamo** [comment]
@byte Should I remove the _events_ option from documentation?

**Comment by byte** [comment]
verify that this does not actually exist, see the mariadb docs which are correct
https://mariadb.com/docs/reference/mdb/system-variables/wsrep_trx_fragment_unit/
