### ISSUE TITLE
Document how to read GRA_*.log files 

### ISSUE THREAD

**Issue by ylacancellera** [codership/documentation#304]
To my knowledge, no documentation show how to read GRA_*.log files

Rare links that talk about it show a hard method : 
https://www.percona.com/blog/2012/12/19/percona-xtradb-cluster-pxc-what-about-gra_-log-files/
https://community.pivotal.io/s/article/How-to-decode-Galera-GRA-logs-for-MySQL-for-PCF-v1-10?language=en_US

I just found out today all I needed was to execute `strings /var/lib/mysql/GRA_a_b.log`

I think it could be worth it

**Comment by kirjaamo** [comment]
@byte Can I solve this by adding:

```
.. code-block:: bash
   #!/bin/bash
   strings /var/lib/mysql/GRA_a_b.log
```
to section _Monitoring a Galera Cluster_ where we talk about the GRA_*.log file?

**Comment by byte** [comment]
> @byte Can I solve this by adding:
> 
> ```
> .. code-block:: bash
>    #!/bin/bash
>    strings /var/lib/mysql/GRA_a_b.log
> ```
> 
> to section _Monitoring a Galera Cluster_ where we talk about the GRA_*.log file?

you can talk about using `strings` and also just running it with `mysqlbinlog`

some sample output

[root@galerasf mysql]# strings GRA_2_123440_v2.log 
binM
8.0.26
CREATE UNDO TABLESPACE undo_003 ADD DATAFILE 'undo_003.ibu'
[root@galerasf mysql]# mysqlbinlog GRA_2_123440_v2.log 
# The proper term is pseudo_replica_mode, but we use this compatibility alias
# to make the statement usable on server versions 8.0.24 and older.
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#230713  6:35:57 server id 1  end_log_pos 0 	Start: binlog v 4, server v 8.0.26 created 230713  6:35:57 at startup
ROLLBACK/*!*/;
BINLOG '
TZuvZA8BAAAAeQAAAAAAAAAAAAQAOC4wLjI2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABNm69kEwANAAgAAAAABAAEAAAAYQAEGggAAAAICAgCAAAACgoKKioAEjQA
CigAbVYcMQ==
'/*!*/;
# at 125
#230713  6:35:57 server id 1  end_log_pos 0 	Query	thread_id=2256014	exec_time=0	error_code=0
SET TIMESTAMP=1689230157/*!*/;
SET @@session.pseudo_thread_id=2256014/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1168113696/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
/*!80011 SET @@session.default_collation_for_utf8mb4=255*//*!*/;
CREATE UNDO TABLESPACE undo_003 ADD DATAFILE 'undo_003.ibu'
/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;

first link on percona site is valid

the pivotal one, is dead
