### ISSUE TITLE
Document donor-timout and joiner-timeout in SST 

### ISSUE THREAD

**Issue by byte** [codership/documentation#308]
Hi!

We need to document:  donor-timeout and joiner-timeout in sst section

Based on this commit
 https://github.com/codership/mysql-wsrep-bugs/commit/f00e45f10e62928a5759983fe9bbf06f44675974

**Comment by kirjaamo** [comment]
@byte Is this ticket still valid? If it is, can I get access to the link or can you copy the necessary parts from the bug here?

**Comment by kirjaamo** [comment]
@byte The current descriptions are here:

![image](https://github.com/user-attachments/assets/a6fe183e-74cc-4d22-bbb7-49577ec238c9)
