### ISSUE TITLE
Update minimum requirements

### ISSUE THREAD

**Issue by byte** [codership/documentation#310]
with some of these requirements, mysql 8 might fail to start. 0.5GB of RAM is quite little

https://galeracluster.com/library/training/tutorials/galera-installation.html

**Comment by kirjaamo** [comment]
@byte Can I solve this by adding 1 GB RAM, or do you want to add more requirements?

**Comment by byte** [comment]
> @byte Can I solve this by adding 1 GB RAM, or do you want to add more requirements?

there are more requirements (you might also just want to look at the MySQL minimum requirements as a good start)

**Comment by kirjaamo** [comment]
For MySQL Server, there are no requirements on MySQL documentation. I guess the requirements depend on the use case. 

Maybe we should give the minimum requirements with 1 GB RAM, and state that the recommended hardware depends on how much data you are planning to store in the cluster.

**Comment by byte** [comment]
> @byte For MySQL Server, there are no requirements on MySQL documentation. I guess the requirements depend on the use case.
> 
> Maybe we should give the minimum requirements with 1 GB RAM, and state that the recommended hardware depends on how much data you are planning to store in the cluster.

this is ok, submit a pull request. also mention that we run well in virtual environments (keywords like vmware) and also cloud environments (so suggest a minimum ec2 instance that makes sense)
