### ISSUE TITLE
Garbd documentation mixes execution as a service with standalone execution

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#32]
This page

http://galeracluster.com/documentation-webpages/arbitrator.html

I think mixes the two concepts:

* starting garbd from the command line, passing it options on the command line
* starting garbd as a service, where the options are placed in a configuration file.

The location of the configuration file is not mentioned (it can be different by distro), and the example of a configuration file that is given is wrongly called "init script".

**Comment by kennethpjdyer** [comment]
This certainly clears up a lot of things.  Not seeing the garbd configuration file on my Ubuntu server.  Are there typical locations where it's installed say through Debian and Fedora?  Something to where I can give them a rough idea of the usual places.

**Comment by kennethpjdyer** [comment]
Fixed.
