### ISSUE TITLE
links to new statements

### ISSUE THREAD

**Issue by byte** [codership/documentation#330]
if today, i look for wsrep_slave_threads, it says it has been renamed, but there is no link. would be nice to click wsrep_applied_threads and be taken to that option

https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-slave-threads

for whatever was renamed, this would also be a good idea to fix

**Comment by kirjaamo** [comment]
@byte There are couple of other places, too, with this problem. Do you want me to create links for all of them?

**Comment by byte** [comment]
> @byte There are couple of other places, too, with this problem. Do you want me to create links for all of them?

yes please @kirjaamo
