### ISSUE TITLE
documentation has no mention of PS protocol

### ISSUE THREAD

**Issue by byte** [codership/documentation#332]
we have --ps-protocol and the documentation is silent on what the PS protocol is

**Comment by kirjaamo** [comment]
@byte , is this a Galera Variable? Is the description below ok?

Run as many SQL statements as possible as prepared statements.

**Comment by temeo** [comment]
I believe this refers to MTR suite option `--ps-protocol`, https://dev.mysql.com/doc/internals/en/variation-of-protocol-option.html. I don't think it make sense to document it in Galera Cluster documentation.

**Comment by byte** [comment]
> I believe this refers to MTR suite option `--ps-protocol`, https://dev.mysql.com/doc/internals/en/variation-of-protocol-option.html. I don't think it make sense to document it in Galera Cluster documentation.

If we are spending a lot of time improving --ps-protocol, do we not presume someone else besides us, would want to run it?

At least a short mention referring to its existence (we btw, have mentioned it in release notes, maybe once in recent times)

**Comment by kirjaamo** [comment]
It is mentioned in release notes. If I mention that it is supported, should I add it to section Galera Parameters?

**Comment by byte** [comment]
OK, teemu and I discussed this, and we can just maybe refer to the MySQL docs rather than doing our own.

**Comment by kirjaamo** [comment]
Do you want me to add it to Galera Parameters and place a link to MySQL docs?
