### ISSUE TITLE
It is 2022

### ISSUE THREAD

**Issue by byte** [codership/documentation#345]
Can we change copyright notices from 2021 -> 2022
https://galeracluster.com/library/training/tutorials/starting-cluster.html

**Comment by kirjaamo** [comment]
I cannot change the year in the footer. No write rights. Yet.

**Comment by kirjaamo** [comment]
We agreed with Teemu that a new doc version will be released on Monday. That version will also fix the copyright year issue. This is already fixed in the source, just not released yet.

**Comment by kirjaamo** [comment]
Fixed.
