### ISSUE TITLE
selinux policy generation

### ISSUE THREAD

**Issue by grooverdan** [codership/documentation#36]
how to generate a policy

<pre>
semanage port -a -t mysqld_port_t -p tcp 4567
semanage port -a -t mysqld_port_t -p udp 4567
semanage port -a -t mysqld_port_t -p tcp 4444

semanage permissive -a mysqld_t
restart mysqld

# do stuff to generate a IST a SST and anything else (notify script)?.

fgrep mysqld /var/log/audit/audit.log | audit2allow  -m MySQL_galera -o MySQL_galera.te
more MySQL_galera.te

# edit as required.

checkmodule -M -m MySQL_galera.te -o  MySQL_galera.mod
semodule_package -m MySQL_galera.mod -o MySQL_galera.pp   
semodule -i MySQL_galera.pp

# remove permissive mode:
semanage permissive -d mysqld_t
</pre>

**Comment by kennethpjdyer** [comment]
Content now in selinux.rst file on draft branch.  Will be pushed to the website in a week or so.

**Comment by grooverdan** [comment]
fyi - https://github.com/MariaDB/server/tree/10.1/support-files/policy/selinux contains a more complete selinux policy that should be usable by galera.
