### ISSUE TITLE
gcache.page_size typo in dbconfiguration.rst

### ISSUE THREAD

**Issue by lbragstad** [codership/documentation#37]
When referencing the database configuration documentation [1], there is a typo in the following line:

```wsrep_provider_options="gcache.size=32G; gachce.page_size=1G"```

which I believe should be:

```wsrep_provider_options="gcache.size=32G; gcache.page_size=1G"```

[1] https://github.com/codership/documentation/blob/master/galeracluster/source/dbconfiguration.rst#basic-wsrep-provider-settings

**Comment by kennethpjdyer** [comment]
The examples you cite look identical.  Am I missing something?  Do you mean the space between the options in the quotes?

**Comment by lbragstad** [comment]
Specifically `gachce.page_size=1G` from the first line above.

**Comment by kennethpjdyer** [comment]
Ah, I see it now.  It was fixed by accident during the last update when this block was moved to configuration.rst.
