### ISSUE TITLE
Where did the limitations page go?

### ISSUE THREAD

**Issue by byte** [codership/documentation#371]
We once had it https://web.archive.org/web/20181104034812/https://galeracluster.com/documentation-webpages/limitations.html

It is now gone

Why?

**Comment by kirjaamo** [comment]
@byte It has been removed as a title from _Tutorials_. However, the _Differences_ file is still there, you can find it with the search function.

If it is gone by purpose, I don't know why. I have not removed it.

**Comment by kirjaamo** [comment]
I don't know. But if you want to add it back to _Tutorials_, I guess it can be done.

**Comment by kirjaamo** [comment]
@byte This page is now back in Tutorials. I think we can close this issue, unless you know of some unlinked articles.
