### ISSUE TITLE
wsrep_recover

### ISSUE THREAD

**Issue by byte** [codership/documentation#374]
We included wsrep_recover script since 8.0.27 but it doesn't have a documentation page. It will be in crash recovery, but we should also be documenting all our helper scripts, which version they came in, etc.

this is /usr/bin/wsrep_recover

https://galeracluster.com/2022/02/galera-cluster-for-mysql-8-0-27-and-5-7-36-released-progress-reporting-for-sst/

**Comment by sciascid** [comment]
By the way, the wsrep_recover script is currently not available in 5.7. However, it was recently back ported and should be part of the next release.

**Comment by kirjaamo** [comment]
@byte  wsrep_recover script is mentioned in the crash recovery page. Can we close this issue?

**Comment by byte** [comment]
> @byte wsrep_recover script is mentioned in the crash recovery page. Can we close this issue?

no, if you read my comment, while it is included in the crash recovery page, where is the "man" page for wsrep_recover script? We need a separate page to talk about it

**Comment by kirjaamo** [comment]
@byte What shall we say in the separate page for wsrep_recover script?

**Comment by byte** [comment]
Taken from 8.4.2

root@node1:~# wsrep_recover --help
Usage: sudo wsrep_recover [options]
Recover database to consistent state, find the last committed GTID and print
corresponding --wsrep-start-position option to standard output (to be used in
startup scripts)

Options for the most part will be passed through directly to mysqld.
Some options have a special meaning though (NOTE whitespace between the option 
name and the value):
  --basedir /x/y/z        will additionally set mysqld binary path to
                          /x/y/z/bin/mysqld
  --mysqld /x/y/z/mysqld  will override --basedir effect on mysqld binary path

For example to run in a totally non-standard setup:

$ sudo wsrep_recover --mysqld /path/to/mysqld --datadir /path/to/datadir --user some_user

By default mysqld binary is expected to be found at '/usr/sbin/mysqld' 
and will be run as 'mysql' user using config from a standard location.

**Comment by kirjaamo** [comment]
@byte I am planning to create a page called _Utility Scripts_ under the _ADMINISTRATION_ section on the _Documentation_ page. To start with, _wsrep_recover Script_ will be the first subheading on that page. Does this sound ok to you?

**Comment by byte** [comment]
> @byte I am planning to create a page called _Utility Scripts_ under the _ADMINISTRATION_ section on the _Documentation_ page. To start with, _wsrep_recover Script_ will be the first subheading on that page. Does this sound ok to you?

yes ok
