### ISSUE TITLE
mysqld_bootstrap --wsrep-new-cluster

### ISSUE THREAD

**Issue by byte** [codership/documentation#375]
As recently pointed out, mysqld can take the option like --wsrep-new-cluster, but on Galera Cluster, we can bootstrap with just: mysqld_bootstrap (it doesn't take any arguments)

@kirjaamo can you find all examples, and fix naturally?

https://galeracluster.com/library/training/tutorials/starting-cluster.html

This should not only change:
mysqld_bootstrap --wsrep-new-cluster

to be mysqld_bootstrap

but not just that, because you might consider changing text around, "To start the first node–which should have MySQL, MariaDB or Percona XtraDB Cluster, and Galera installed–you’ll have to launch the database server on it with the --wsrep-new-cluster option."

**Comment by kirjaamo** [comment]
Fixed and merged
