### ISSUE TITLE
Update wsrep_start_position documentation

### ISSUE THREAD

**Issue by byte** [codership/documentation#383]
https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-start-position

commit 2fec3a36615a94f0a812a140599f7cdd9b64e6a1
- wsrep_start_position contains the wsrep GTID position, local seqno for asynchronous replication, server ID and server UUID all in one argument, slash-separated

**Comment by kirjaamo** [comment]
@byte Do you mean that this string in the default value field:

00000000-0000-0000-0000-00000000000000:-1

should be like this:

00000000/0000/0000/0000/00000000000000:/1

**Comment by byte** [comment]
This is what I see now, @kirjaamo 

mysql> SHOW VARIABLES LIKE 'wsrep_start_position';
+----------------------+----------------------------------------------------------------------------------+
| Variable_name        | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| wsrep_start_position | 00000000-0000-0000-0000-000000000000:-1/0/0/00000000-0000-0000-0000-000000000000 |
+----------------------+----------------------------------------------------------------------------------+
1 row in set (0.01 sec)
