### ISSUE TITLE
Document wsrep_sync_server_uuid

### ISSUE THREAD

**Issue by byte** [codership/documentation#384]
commit de1062ad0aa92ea9ad7b0a7b0ef1149b2c47a45b

    Introduce wsrep_sync_server_uuid configuration variable. If set to true
    the node respects server UUID received from the donor node. Otherwise
    the node generates its own server UUID. This concerns only binlog events
    not replicated via wsrep which continnue to be logged with cluster UUID.
    
    Refs codership/mysql-wsrep-bugs#1372

**Comment by kirjaamo** [comment]
How can I find this: codership/mysql-wsrep-bugs#1372?

**Comment by byte** [comment]
> How can I find this: [codership/mysql-wsrep-bugs#1372](https://github.com/codership/mysql-wsrep-bugs/issues/1372)?

Not quite needed, extract:
Problem: wsrep nodes keep generating their own individual server UUIDs which are used to binlog events that are not replicated via wsrep, like rolling schema upgrades and such. This makes such individual node histories incomparable and considerably complicates switching asynchronous slave MASTER between the nodes in the cluster.

Force the nodes to use the same server UUID (generated on the seed node) to binlog events that don't go through wsrep. This should make the histories comparable provided the user executes such operations in agreed order on all the nodes.

**Comment by byte** [comment]
merged pr https://github.com/codership/documentation/pull/413
