### ISSUE TITLE
Add notes to discourage users from changing repl.commit_order setting

### ISSUE THREAD

**Issue by denis-protivensky** [codership/documentation#390]
Related JIRA ticket: https://jira.mariadb.org/browse/MDEV-31532

**Comment by byte** [comment]
@denis-protivensky the documentation states several types of repl.commit_order

Are they supposed to never be changed from the default which happens to be 3?

https://galeracluster.com/library/documentation/galera-parameters.html#repl-commit-order

**Comment by denis-protivensky** [comment]
Other values may produce inconsistencies or even lead to server crashes (it's a known issue as well). Changing the default is not recommended.

**Comment by byte** [comment]
@kirjaamo please update the documentation to ensure people do not change the default

@denis-protivensky tells me there is TODO to ensure that the option itself will eventually be deprecated. But in the meantime, let's get the docs updated to ensure people do not use it
