### ISSUE TITLE
MariaDB install out of date

### ISSUE THREAD

**Issue by byte** [codership/documentation#397]
https://galeracluster.com/library/documentation/install-mariadb.html

This is out of date. It even references 5.6 which is incorrect

e.g. on centos 7 you need to get epel enabled, to have pv utility installed, so command like:
yum -y install epel-release

must be included in the documentation.

I think we have to focus on testing it on 10.6 and 10.11 which are the LTS releases

**Comment by kirjaamo** [comment]
@byte Do you have a link where the current MariaDB installation is described?

**Comment by byte** [comment]
@kirjaamo i do not even guarantee this is correct, but it is better tha what we have https://mariadb.com/kb/en/getting-started-with-mariadb-galera-cluster/

ours just needs to be updated, not... replaced with the above

**Comment by kirjaamo** [comment]
@byte Shoud I include installing the arbitrator?

**Comment by byte** [comment]
> @byte Shoud I include installing the arbitrator?

i think not in this, no

**Comment by kirjaamo** [comment]
@byte Is my draft otherwise ok?

**Comment by kirjaamo** [comment]
@byte Can we close this ticket?
