### ISSUE TITLE
Missing and invalid parameter descriptions

### ISSUE THREAD

**Issue by temeo** [codership/documentation#4]
<a href="https://github.com/temeo"><img src="https://avatars.githubusercontent.com/u/6009633?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [temeo](https://github.com/temeo)**
_Tuesday May 06, 2014 at 12:19 GMT_
_Originally opened as https://github.com/codership/galera/issues/12_

----

Originally reported here: https://groups.google.com/forum/#!topic/codership-team/O4vHuGBKRC0

http://galeracluster.com/documentation-webpages/galeraparameters.html - `'replication.*'` should be `'repl.*'`.

missing options on this page: 
* `socket.checksum`
* `repl.key_format` 
* `repl.proto_max` 
* `repl.max_ws_size`
* `pc.announce_timeout` 
* `pc.wait_prim_timeout`
* `gmcast.segment`
* `base_host`
* `base_port`
* `cert.log_conflicts`

other suggestions: 

4.16.6 selinux - a link to https://blogs.oracle.com/jsmyth/entry/selinux_and_mysql would probably help 

5.3.1. Diagnosing Multi-Master Conflicts 

could include a reference to cert.log_conflicts

**Comment by kennethpjdyer** [comment]
wsrep Provider options are all now documented on galeraparameters.  Will work on the 'other suggestions' soon.

**Comment by kennethpjdyer** [comment]
The 'other suggestions' have already been addressed.
