### ISSUE TITLE
Check wsrep_OSU_method

### ISSUE THREAD

**Issue by byte** [codership/documentation#418]
Hi Codership.

I think this page has an issue:

https://galeracluster.com/documentation/html_docs_20231215-0627-master/documentation/schema-upgrades.html

It says "SET GLOBAL wsrep_OSU_method ..."

However, GLOBAL won't actually change the wsrep_OSU_method for the session you're in. Which is the session I suspect most readers will want to use for their ALTER TABLE.

You may want to clarify that for your readers.

**Comment by kirjaamo** [comment]
@byte In WSREP options, we say that this is both global and session scope variable. Is it only global?

**Comment by kirjaamo** [comment]
There is also a typo in the RST file:

![image](https://github.com/user-attachments/assets/4fcb0738-243e-4e1d-b877-35aedb7cc59f)

**Comment by byte** [comment]
> @byte In WSREP options, we say that this is both global and session scope variable. Is it only global?

it is global and session

please also fix the typo in a PR thanks @kirjaamo

**Comment by kirjaamo** [comment]
@byte The original change request was that "GLOBAL won't actually change the wsrep_OSU_method for the session you're in."

Should I add a note that "GLOBAL does not change the wsrep_OSU_method for the current session". And/or should we provide more instructions for changing the wsrep_OSU_method for the ALTER TABLE command?

**Comment by byte** [comment]
> @byte The original change request was that "GLOBAL won't actually change the wsrep_OSU_method for the session you're in."
> 
> Should I add a note that "GLOBAL does not change the wsrep_OSU_method for the current session". And/or should we provide more instructions for changing the wsrep_OSU_method for the ALTER TABLE command?

the note you should be adding is quite clear from here for example 

https://mariadb.com/docs/server/sql/statements/schema/online-schema-changes/enterprise-server/galera/

Dynamically Changing an Operation's Online Schema Change Method

and

Dynamically Changing the Server's Online Schema Change Method

We currently are for the server's (second) not operations (first)

the docs are correct, just a tad confusing, so specify both
