### ISSUE TITLE
Wrong sentence: "To see retrieve the value of this status variable"

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#422]
The page that list galera status variables contains the following sentence "To see retrieve the value of this status variable, execute the SHOW STATUS statement like so", at the end of each status variable.
This should be fixed with "To see the value of" or "To retrieve the value of", not both "see retrieve".

https://galeracluster.com/library/documentation/galera-status-variables.html

**Comment by byte** [comment]
fixed, thanks for reporting @sciascid
