### ISSUE TITLE
wsrep_convert_LOCK_to_trx is deprecated

### ISSUE THREAD

**Issue by byte** [codership/documentation#431]
in the next release of MySQL 8, wsrep_convert_LOCK_to_trx will be deprecated. it is currently dead code. documentation has to reflect this, since this option is actually not implemented anyway.

note that even percona deprecated it https://forums.percona.com/t/percona-xtradb-and-wsrep-convert-lock-to-trx/17782

it should stick in the docs for 5.7 but made to note it doesnt work in 8.0

**Comment by kirjaamo** [comment]
We usually give a detailed version as of which the option is deprecated, like:

`"Deprecated Version", "MySQL-wsrep: 8.0.19-26.3, MariaDB: 10.1.1"`

What is the exact version where _wsrep_convert_LOCK_to_trx_ is deprecated?

**Comment by kirjaamo** [comment]
@byte Can I say "Deprecated as of version MySQL-wsrep: 8.0.19-26.3"?

**Comment by byte** [comment]
Yes you can

Colin Charles, http://www.bytebot.net/
"First they ignore you, then they laugh at you, then they fight you, then
you win." -- Mohandas Gandhi

**Comment by byte** [comment]
fixed https://github.com/codership/documentation/pull/438
