### ISSUE TITLE
Option wsrep_ws_persistency does not exist

### ISSUE THREAD

**Issue by sciascid** [codership/documentation#432]
Option wsrep_ws_persistency is documented here: https://galeracluster.com/library/documentation/mysql-wsrep-options.html

However, this option does not seem to exist in mysql-wsrep nor mariadb.
This should be declared deprecated or removed altogether from documentation.

**Comment by kirjaamo** [comment]
@byte Can I remove this?

**Comment by byte** [comment]
Actually the documentation does list: 

Deprecated Version | MySQL-wsrep: 5.1.59-22.2
-- | --


And it has been so long since 5.1 existed... I think it might be safe to remove it @kirjaamo
