### ISSUE TITLE
CLONE SST is now default in 8.4.2

### ISSUE THREAD

**Issue by byte** [codership/documentation#440]
while not true for 8.0, it is for 8.4.2 and needs to be documented as such

**Comment by kirjaamo** [comment]
@byte Is it enough, if I add "As of 8.4.2, it is the default value for SST methods" to this page as the second sentence.

![image](https://github.com/user-attachments/assets/80e3a8b5-cde5-430a-8072-b72678a85a1d)

**Comment by kirjaamo** [comment]
Note to self. There is also a typo: "configuraition" -> "configuration".

**Comment by byte** [comment]
@kirjaamo yes, go for it
