### ISSUE TITLE
Replace MASTER/SLAVE with SOURCE/REPLICA

### ISSUE THREAD

**Issue by kirjaamo** [codership/documentation#461]
Gradually, we should stop using master/slave like upstream has changed overall. MariaDB has begun the process of adding _primary_ and _replica_ synonyms. MySQL seems to be using _source_ and _replica_ synonyms.

This covers:

- Update new statements from MySQL and MariaDB and add them to our documentation. Keep the old syntax. (**DONE and pushed**)
- After discussion, possibly update generic text so that we use source and replica, instead of master and slave.

Changed statements will be: (**DONE and pushed**)

**SHOW MASTER STATUS**

- MySQL: SHOW BINARY LOG STATUS
- MariaDB: SHOW MASTER STATUS

**SHOW SLAVE STATUS**

- MySQL: SHOW REPLICA STATUS
- MariaDB: SHOW REPLICA STATUS

**CHANGE MASTER TO**
- Already fixed for MySQL (CHANGE REPLICATION SOURCE TO)
- MariaDB uses CHANGE MASTER TO

**STOP SLAVE**

- MySQL: STOP REPLICA
- MariaDB: STOP SLAVE

**START SLAVE**

- MySQL: START REPLICA
- MariaDB: START SLAVE

**Comment by byte** [comment]
for MariaDB Server, please pay attention to https://jira.mariadb.org/browse/MDEV-18777

**Comment by byte** [comment]
i think this is done, but if anyone finds issues, new bug can be opened
