### ISSUE TITLE
Update wsrep options

### ISSUE THREAD

**Issue by kirjaamo** [codership/documentation#464]
1. _wsrep_applier_threads_ and _wsrep_sst_receive_address_ are dynamic variables. In our documentation, the _Dynamic Variable_ field is empty for those variables. Add _Yes_ to them.
2. _wsrep_sync_wait_: update with MariaDB-specific options from here: https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_sync_wait

**Comment by byte** [comment]
fixed 2. wsrep_sync_wait which isn't mariadb only
