### ISSUE TITLE
Tally galera version with mysql release version

### ISSUE THREAD

**Issue by byte** [codership/documentation#469]
this involves going thru releases, one by one.

focus on 8.0 first. 

8.4 is easy, there is only one.

then do 5.7 for legacy purposes.

Model it after: https://mariadb.com/kb/en/what-is-mariadb-galera-cluster/#galera-versions

Much easier to do here because it is just one 8.0.x version that is linked to a galera 26.4.x release

I suggest also linking to the release notes. A complete list of releases that are still being hosted are here: https://releases.galeracluster.com/

it is manual work, but shouldn't be hard to do.

Take inspiration from https://galeracluster.com/2024/08/galera-cluster-for-mysql-8-0-39-26-20-released/ and other release posts.

See how we have release notes linked, download (point to the release notes of the server itself). 

sometimes there is no change in the galera replication library, so link to the older release as well.

make it a table.

**Comment by kirjaamo** [comment]
Do you mean something like this:
| Galera Version | Released in MySQL Version |
| ---------------- |:------------------------------:|
| 8.4.2-26.20       | 8.4.2                                    |
| 8.0.39-26.20     | 8.0.39                                  |

**Comment by kirjaamo** [comment]
+ the link

**Comment by byte** [comment]
@kirjaamo not quite

galera version | released with MySQL version
4.20 | 8.0.39-26.20
4.19 | 8.0.37-26.19

and so on

second line from https://galeracluster.com/2024/07/galera-cluster-for-mysql-8-0-37-26-19-released/

**Comment by kirjaamo** [comment]
@byte On 5.7, the latest match between version numbers is Galera 3.37 and MySQL 5.7.37-25.29. However, there are MySQL release notes up to 5.7.44-25.36. In which Galera version are MySQL 5.7.38-25.30 - 5.7.44-25.36?

**Comment by kirjaamo** [comment]
@byte Should I make the links to the release notes in this structure: https://releases.galeracluster.com/

https://galeracluster.com/2024/07/galera-cluster-for-mysql-8-0-37-26-19-released/ is also good, but we don't have such pages for all releases.

**Comment by byte** [comment]
> @byte On 5.7, the latest match between version numbers is Galera 3.37 and MySQL 5.7.37-25.29. However, there are MySQL release notes up to 5.7.44-25.36. In which Galera version are MySQL 5.7.38-25.30 - 5.7.44-25.36?

sometimes you'll notice the release notes state a mysql will use the same older galera library, this is perfectly ok

**Comment by byte** [comment]
> @byte Should I make the links to the release notes in this structure: https://releases.galeracluster.com/
> 
> https://galeracluster.com/2024/07/galera-cluster-for-mysql-8-0-37-26-19-released/ is also good, but we don't have such pages for all releases.

release notes at releases.galeracluster.com + why not also a link to the blog. lets be complete. there is definitely such a place for all 5.7 and 8 and 8.4 releases - i know, i wrote most of them ;)

**Comment by kirjaamo** [comment]
@byte Ok. I'll try to find the correct posts for different releases.
