### ISSUE TITLE
separate release notes section in documentation

### ISSUE THREAD

**Issue by sjaakola** [codership/documentation#474]
Currently it is not straight forward to find release notes of past cluster releases (I have heard people scanning fromdual site to find our release notes)

The documentation should have a separate section to list all published releases with release dates, version numbers and release notes

**Comment by kirjaamo** [comment]
@sjaakola Fixed last week.

**Comment by byte** [comment]
fixed, https://galeracluster.com/documentation/library/documentation/versions-and-release-notes.html#versions-and-release-notes
