### ISSUE TITLE
wsrep_mode variable documentation is not complete

### ISSUE THREAD

**Issue by sjaakola** [codership/documentation#478]
wsrep_mode variable allows several "flags" for configuring the replication behavior. Current documentation does not show all possible flags, and documentation should be extended to cover all choices.

In MySQL side, we have flags:
```
grep -A5 "wsrep_mode_names\[\]" sql/sys_vars.cc
static const char *wsrep_mode_names[]= 
{ "IGNORE_NATIVE_REPLICATION_FILTER_RULES",
  "IGNORE_CASCADING_FK_DELETE_MISSING_ROW_ERROR",
  "APPLIER_IGNORE_MISSING_TABLE",
  "APPLIER_SKIP_FK_CHECKS_IN_IST",
  NullS
```

MariaDB, otoh, has different flags:

```
 grep -A9 "wsrep_mode_names\[\]" sql/sys_vars.cc
static const char *wsrep_mode_names[]=
{
  "STRICT_REPLICATION",
  "BINLOG_ROW_FORMAT_ONLY",
  "REQUIRED_PRIMARY_KEY",
  "REPLICATE_MYISAM",
  "REPLICATE_ARIA",
  "DISALLOW_LOCAL_GTID",
  "BF_ABORT_MARIABACKUP",
  NullS
```
Both sets of flags should be presented.

Note that new flags may be introduced by bug fixing and new feature development. e.g. the recent work for https://github.com/codership/mysql-wsrep-bugs/issues/1794 added the flag APPLIER_SKIP_FK_CHECKS_IN_IST. Documentation work should be triggered directly from development, we need to improve this process.

**Comment by byte** [comment]
@kirjaamo 

This is for https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-mode

also, for bug listed above:
Appliers need to verify foreign key constraints during normal operation, in multi-active topologies, and for this reason appliers are configured to enable FK checking.

However, during node joining, in IST and latter catch up period, the node is still idle (from local connections), and only source for incoming transactions is the cluster sending certified write sets for applying. IST happens with parallel applying, and there is a possibility that foreign key check cause lock conflicts between appliers accessing FK child and parent tables. Also, the excessive FK checking will slow down IST process somewhat.

For this reasons, we could relax FK checks for appliers during IST and catch up periods. The relaxed FK check mode should, however, be configurable e.g. by wsrep_mode flag: SKIP_APPLIER_FK_CHECKS_IN_IST. When this operation mode is set, and the node is processing IST or catch up, appliers should skip FK checking.

to be very complete, make sure we also list Percona XtraDB Cluster (PXC) - https://docs.percona.com/percona-xtradb-cluster/8.0/wsrep-system-index.html#wsrep_mode

which only actually has IGNORE_NATIVE_REPLICATION_FILTER_RULES

So, for MySQL we are missing:
IGNORE_NATIVE_REPLICATION_FILTER_RULES (eventhough this is listed as an example)
IGNORE_CASCADING_FK_DELETE_MISSING_ROW_ERROR
APPLIER_SKIP_FK_CHECKS_IN_IST

and for mariadb you can pull from here: https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_mode

**Comment by sjaakola** [comment]
IGNORE_CASCADING_FK_DELETE_MISSING_ROW_ERROR seems to a work around for a mysql bug: https://bugs.mysql.com/bug.php?id=80821

The flag was added in our repositories by commit:
commit cb0441b0fa74453763fdc537af1b409b9cc32247
Author: Leandro Pacheco <leandro.pacheco@galeracluster.com>
Date:   Tue Aug 10 17:32:50 2021 -0300

    add new wsrep_mode IGNORE_CASCADING_FK_DELETE_MISSING_ROW_ERROR
    
    Work around mysql bug #80821. On cascading deletes, when both parent and child
    are involved in the query, a delete rows event for the child may be added to the
    binlog after the parent (cascading) delete. This will cause the delete to fail
    on slaves. This commit causes such errors to be ignored on slaves when wsrep_mode
    includes the new option IGNORE_CASCADING_FK_DELETE_MISSING_ROW_ERROR
    
    The test galera.galera_fk_multitable was affected by the bug and has been
    re-enabled with the warning suppressed.

The upstream problem may be fixed already, and this flag could therefore be obsolete by now

**Comment by kirjaamo** [comment]
@byte Two of the MariaDB flags are described in MariaDB options: `REPLICATE_ARIA` and `REPLICATE_MYISAM`. They have a note:

This functionality is experimental and should not be relied upon in production systems. 

I'm planning to keep all flags in the _MySQL wsrep Options_ page. Should I include the note?

**Comment by sjaakola** [comment]
APPLIER_IGNORE_MISSING_TABLE was added by commit:

commit aca1f9acfe43f398b050a3f2d5e0ff967ebf5c27 (origin/8.0-v26-trigger_tablemap-merge)
Author: Teemu Ollakka <teemu.ollakka@galeracluster.com>
Date:   Tue Feb 21 14:21:08 2023 +0200

    codership/mysql-wsrep-bugs#1362 multi table update on table with triggers
    
    Merged manually test and fix from 5.7-v25, commits
    

    codership/mysql-wsrep-bugs#1362 multi table update on table with triggers
    
    Merged manually test and fix from 5.7-v25, commits
    
    f398e901d8b374547a25a41557587384e6259483
    e0f0c73eba7fccb61c63564fcb1a689262e78163
    98edd3d12a75f6befcac18ec5e39e92b7ed86831
    
    Original commit message for the fix:
    
        Created a mtr test causing crash if multi tabe update is executed on table used for join (read only) and has triggers.
        The test renames the triggered table while the update is replicating, this causes the crash if applier cannot open the triggered table, which was just renamed.
    
        Implemented a "naive fix" for the issue.
        In this design, the excessive tablemap event remains in binlog, but applier and replayer are relaxed to ignore failure in opening a table.
        This means they ignore all open table errors, regardlesss if the failure in open was related to excessive triggered table opening or not.
        The assumption is that, if the table open error is a real problem, then applying will fail later on with some other error.
    
        Fix to make sure that ignored table does not remain in table cache
        addition to mtr test to verify that table cache does not contains remnants of the zombie table
    
        Fix to raise error and crash the node, if applying fails to open all tables
    
        fixed test galera_trigger_binlog to be deterministic
    
        added two new test cases
    
        Changed the fix to be conditional and configured by wsrep_mode.
        Added new wsrep_mode: APPLIER_IGNORE_MISSING_TABLE, which enables the
        fix to skip failures with table open at applying time, but only if
        the log event contains also other tables, which are sucessfully opened.
        APPLIER_IGNORE_MISSING_TABLE option is set as default mode in this commit.
    
        The fix is now extended to raise error, if there is a real inconsistency in the database,
        so that a table is really missing, and a multi table operation (like UPDATE)
        using also the missing table.
    
        Recorded new result for galera_defaults test, as wsrep_mode has new default value: APPLIER_IGNORE_MISSING_TABLE
    
    Adapted the test galera_trigger_binlog to work with error voting.
    Instead of expecting the server to shut down, wait it to become
    disconnected after voting round.
    
    Recorded galera.galera_defaults and main.mysqld--help-notwin for
    changed wsrep_mode default.

**Comment by sjaakola** [comment]
IGNORE_NATIVE_REPLICATION_FILTER_RULES I cannot find in commit logs, but this is simply to choose if native async replication filtering options should be honored in galera replication applying. These options are of format replicate_* and specify if transactions for some table or database should be applied or not

**Comment by kirjaamo** [comment]
@sjaakola What does `BF_ABORT_MARIABACKUP` do?

**Comment by kirjaamo** [comment]
@byte Should I add to MariaDB Strict_Replication this (taken from here: https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_strict_ddl): 

If set, rejects DDL statements on affected tables not supporting Galera replication. This is done by checking if the table is InnoDB, which is the only table currently fully supporting Galera replication. MyISAM tables will not trigger the error if  WSREP_REPLICATE_MYSISAM setting is ON. If set, should be set on all tables in the cluster.
