### ISSUE TITLE
Document new package repositores

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#48]
We now have our own package repositories, so the download installation instructions need to be updated to reflect that fact.

For CentOS, Fedora:

1. Create a file ```/etc/yum.repos.d/galera.repo``` with the following contents:

```
[galera]
name=Galera
baseurl=http://releases.galeracluster.com/DIST/RELEASE/x86_64
gpgcheck=1
gpgkey=http://releases.galeracluster.com/GPG-KEY-galeracluster.com
```

replacing ```DIST``` with ```centos``` or ``fedora`` and ```RELEASE``` is the OS release number, e.g. 6,7 for Centos  , 20, 21 for Fedora

2. Install packages:

```
sudo yum install galera-3
sudo yum install mysql-wsrep-5.6
```

Package ```galera-3``` will install Galera wsrep provider and garbd. Package ```mysql-wsrep-5.6``` will install MySQL server and client components.

For OpenSuse, SLES:

1. Import GPG key:

```
sudo rpm --import "http://releases.galeracluster.com/GPG-KEY-galeracluster.com"
```

2. Create a ```galera.repo``` file in local directory. 

```
[galera]
name=Galera
baseurl=http://releases.galeracluster.com/DIST/RELEASE/x86_64
gpgcheck=1
```

replacing ```DIST``` with ```opensuse```, or ```sles``` and RELEASE with version number

3. Install repository:

```
    sudo zypper addrepo galera.repo
    sudo zypper refresh

    sudo zypper install galera-3
    sudo zypper install mysql-wsrep-5.6
```

For Ubuntu, Debian:

1. Install key

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA
```

2. Install the Galera package repository.

Create a file named ```/etc/apt/sources.list.d/galera.list``` with the following content:

```
deb http://releases.galeracluster.com/DIST RELEASE main
```

where ```DIST``` is either ```ubuntu``` or ```debian``` and ```RELEASE``` is the release codename (```precise```, ```trusty``` for Ubuntu, ```wheezy``` for Debian).

3. Install packages:

```
    sudo apt-get update --ignore-missing
    sudo apt-get install galera-3 galera-arbitrator-3
    sudo apt-get install mysql-wsrep-5.6
```

**Comment by temeo** [comment]
@kennethpjdyer The final documentation in http://galeracluster.com/documentation-webpages/installmysql.html states that user should install also mysql-client-5.6 packages. This should not be necessary as mysql-wsrep-5.6 installs also client binaries.

Also, I think ```--ignore-missing``` in
```
apt-get update --ignore-missing
```
is not needed.

**Comment by philip-galera** [comment]
```

Small typo in yum repo URL at 


http://galeracluster.com/documentation-webpages/installmysql.html#enabling-the-yum-repository


s/release.galeracluster.com/releases.galeracluster.com
```

**Comment by ayurchen** [comment]
Actually, 4 typos ;) All fixed in https://github.com/codership/documentation/commit/7198e081233f9df6110aa141490215af96be2dba
