### ISSUE TITLE
Update Documentation Site Theme

### ISSUE THREAD

**Issue by temeo** [codership/documentation#6]
<a href="https://github.com/kennethpjdyer"><img src="https://avatars.githubusercontent.com/u/6652799?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kennethpjdyer](https://github.com/kennethpjdyer)**
_Thursday May 08, 2014 at 02:18 GMT_
_Originally opened as https://github.com/codership/galera/issues/18_

----

Change the Galera documentation over to the new theme.  
- Adjust the CSS for better readability.
- Push the changes out.  
- Fix and add the Edit on Github link to the lower navigation bar.

**Comment by kennethpjdyer** [comment]
Done.
