### ISSUE TITLE
Integrate the content from http://wiki.codership.com/ into the documentation

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#71]
We have a wiki , http://wiki.codership.com/, which may contain some information not available in the documentation, such as a description of the SST protocol and the conventions for writing new SST scripts.

All content should be integrated into the documentation so that the wiki.codership.com host can be retired.

**Comment by kirjaamo** [comment]
@byte Can I get access to Wiki, please.

**Comment by kirjaamo** [comment]
@byte Or does the wiki still exist?

**Comment by byte** [comment]
nope
