### ISSUE TITLE
OpenStack High Availability Guide mentiones Galera's obsolete launchpad home page

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#74]
This URL

http://docs.openstack.org/high-availability-guide/content/ha-aa-db-mysql-galera.html

mentions launchpad.net , launchpadlibrarian.net , which are obsolete URLs.

Also, the heading says "MySQL version patched for wsrep:" but then the description is about how to install MariaDB Cluster. I guess MariaDB Cluster should be mentioned at all places as the instructions are about how to install it, rather than Galera Cluster.

**Comment by kennethpjdyer** [comment]
Submitted a patch that overhauls the OpenStack Galera docs.  Still trying to get it through the review process.

**Comment by kennethpjdyer** [comment]
Fix to OpenStack docs now in their repo.
