### ISSUE TITLE
wsrep_sync_wait could be more complete

### ISSUE THREAD

**Issue by shinguz** [codership/documentation#75]
available types: 1,2,3,4 this is not a bit mask. Either 1, 2, 4 or then 0 - 7
http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html#wsrep-sync-wait

See competitors: 
https://mariadb.com/kb/en/mariadb/galera-cluster-system-variables/#wsrep_sync_wait
http://www.percona.com/doc/percona-xtradb-cluster/5.5/wsrep-system-index.html

Further I assume (and I think I even checked it?) that this variable can be changed on a session level. If not I expect at least a warning or an error.

Further it would be nice to have explanation/example for use cases where value is != 0/1 or describe negative impacts on wsrep_sync_wait = 6/7

**Comment by philip-galera** [comment]
https://github.com/codership/documentation/issues/18

It is a session variable. It is a bit mask.

**Comment by kennethpjdyer** [comment]
Fixed.
