### ISSUE TITLE
Description of backup procedure via garbd is way off

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#76]
http://galeracluster.com/documentation-webpages/backingupthecluster.html#backing-up-cluster-data

speaks of State Snapshot Transfer being sent to the invoking ```garbd```. It is absolutely wrong. ```garbd``` only triggers the selected node to run a **backup** script. What that script does depends solely on its contents, so it is an opportunity for user to script the backup however he likes.

In any case garbd exits immediately after sending the request and is not participating in the backup process in any way.

See a more accurate description here: https://web.archive.org/web/20130624210537/http://www.codership.com/wiki/doku.php?id=data_backup

**Comment by ayurchen** [comment]
Kenneth, I made a provisional fix in https://github.com/codership/documentation/tree/gh76. Could you please take over and fix the language?

**Comment by kennethpjdyer** [comment]
Will do.

**Comment by philip-galera** [comment]
This is already merged.
