### ISSUE TITLE
Should acronyms be a part of glossary terms?

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#77]
For example right now we have in glossary.rst
    * Global Transaction ID
    * State Snapshot Transfer (SST)
    * Incremental State Transfer (IST)
This makes it impossible to refer to SST definition just by ```State Snapshot Transfer``` or just by ```(SST)```, it must be ```State Snapshot Transfer (SST)``` every time which seems excessive.

At the same time ```Global Transaction ID``` also has a well established acronym ```GTID```, but is is not included in the glossary. So using acronym GTID may be confusing to a first-timer.

Ideally it would be nice to be able to refer to the term both by full name and by acronym. But if it is not possible, we should at least standardize on whether acronym is a part of the term or not.

**Comment by kennethpjdyer** [comment]
I'm going to start a glossary overhaul in a week or two.  I'll look into stripping them out reorganizing their use when I do.
