### ISSUE TITLE
Document that wsrep_node_address is required for multi-region EC2, Azure, etc. clouds

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#78]
An older version of the documentation had this:

"wsrep_node_address

Even though MySQL-wsrep patch tries to autodetect the node address, it cannot reliably do that in all cases and environments. For example in EC2 you may need to set it to the node global DNS name instead of the local interface IP address, and so on."

We should have that in the current documentation as well, as without setting wsrep_node_address it it not possible for Galera nodes from different regions to find each other, so not possible to have a geodistributed database.

**Comment by kennethpjdyer** [comment]
Covered on mysqlwsrepoptions.
