### ISSUE TITLE
Document wsrep_flow_control_paused_ns

### ISSUE THREAD

**Issue by temeo** [codership/documentation#8]
<a href="https://github.com/grypyrg"><img src="https://avatars.githubusercontent.com/u/1330700?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grypyrg](https://github.com/grypyrg)**
_Tuesday Jun 03, 2014 at 07:22 GMT_
_Originally opened as https://github.com/codership/galera/issues/48_

----

wsrep_flow_control_paused_ns is not documented on http://galeracluster.com/documentation-webpages/galerastatusvariables.html#wsrep-flow-control-paused

PXC 5.6 has a brief mention about it: http://www.percona.com/doc/percona-xtradb-cluster/5.6/wsrep-status-index.html

**Comment by kennethpjdyer** [comment]
wsrep_flow_control_paused_ns documented on galerastatusvariables.
