### ISSUE TITLE
"does not matter" versus "makes no difference"

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#80]
A letter from concerned user:
> Good folks @ Galera Cluster,
>
> Thank you first of all for providing such an open source piece of software - it's nothing short of awesome!
>
> Anyway, I am writing to you with a remark / question about the documentation on your website. Due to my "noobness", I might be barking up the wrong tree; if this turns out to be the case, please let me know, and I'll try to find the right place to report this.
>
> Again, being a "noob", I am reading your documentation trying to find out how one such cluster works and is put together. In my research, I've been through the following page:
>
> http://galeracluster.com/documentation-webpages/startingcluster.html
>
> Here, I see a section called "STARTING THE FIRST CLUSTER NODE", wherein the first note says "Note: It does not matter which node you choose to use as your first."
>
> Maybe it is in your interest to understand how it is that I am struggling to understand the meaning of this? What I think (and hope) you mean to say is "It makes no difference which node you choose to use as your first." And perhaps explain that this (again, hopefully) means that if this one first node crashes at some point, the cluster will still be functioning with the other two (or more) nodes because of how it's been built.
> Then again, perhaps I am completely misunderstanding what you mean on this note? If not, what does it mean? I find that "It does not matter" sounds tenuous and could actually mean many things, which is why I'm asking.
>
> Anyway. This is at least something you might want to consider and, if I am lucky, perhaps even provide me with an answer (I'd be a happy camper, lemme tell ya).
>
> With kind regards
> /Alan Jiménez

I'm not so sure about the "does not matter" versus "makes no difference". But it has been clear for a long time that some are struggling to grasp this, namely that the "first" node is the "first" only as long as it is the only one, and as soon as another node (fully) joins the cluster there is no practical difference between them.

It would be nice to come up with a less awkward explanation and put it in the docs.

**Comment by kennethpjdyer** [comment]
Added clarification section to relevant page.
