### ISSUE TITLE
potential error in SSL documentation (LP1463528)

### ISSUE THREAD

**Issue by ayurchen** [codership/documentation#82]
As logged in https://bugs.launchpad.net/galera/+bug/1463528

> There is a small mistake in the documentation: http://galeracluster.com/documentation-webpages/sslcert.html
> Section "VERIFYING THE CERTIFICATES"
```
openssl verify -CAfile ca.pem \
      server-cert.pem client-cert.pem
```
This should be:
```
openssl verify -CAfile ca-cert.pem \
      server-cert.pem client-cert.pem
```

**This must be verified first!**

**Comment by ayurchen** [comment]
Philip, could you verify this or reassign?

**Comment by kennethpjdyer** [comment]
Think it's a typo.  They create a file called ca-cert.pem on the page before.

**Comment by ayurchen** [comment]
Indeed. Thanks for noticing that. Pushed the fix in https://github.com/codership/documentation/commit/dd53fc593ec64ef81cda9af75d40dd91e003e507
