### ISSUE TITLE
Securing Replication Traffic config example error

### ISSUE THREAD

**Issue by temeo** [codership/documentation#83]
In http://galeracluster.com/documentation-webpages/sslconfig.html#securing-replication-traffic the configuration example lists ```socket.ssl_ca``` twice. I guess the first parameter should be ```socket.ssl_key``` instead.

**Comment by ayurchen** [comment]
I think this was fixed in https://github.com/codership/documentation/commit/97fdb90f6d758c7a46acb8f814679d18f16ca600
