### ISSUE TITLE
Document wsrep_log_conflicts in addition to cert.log_conflicts 

### ISSUE THREAD

**Issue by philip-galera** [codership/documentation#87]
Document wsrep_log_conflicts in addition or instead of cert.log_conflicts in dealingwithmultimasterconflicts.rst and any other section that deals with troubleshooting conflicts.

wsrep_log_conflicts provides useful, MySQL-side additional information about the conflict, such as name of table and schema where the conflict occured, as well as the actual values for the keys that produced the conflict.

**Comment by kennethpjdyer** [comment]
Additions made.
