### ISSUE TITLE
Documentation with garbd

### ISSUE THREAD

**Issue by temeo** [codership/documentation#9]
<a href="https://github.com/johankooi"><img src="https://avatars.githubusercontent.com/u/7803900?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johankooi](https://github.com/johankooi)**
_Thursday Jun 05, 2014 at 10:02 GMT_
_Originally opened as https://github.com/codership/galera/issues/52_

----

On Fedora (and maybe some more distributions) there is in the /etc/sudoers file an line which says:
 Defaults    requiretty
You must comment out this line before you can start garbd because in the /etc/init.d/garb there is a sudo -u nobody   statement which fails on the standard sudoers file of Fedora.

**Comment by kennethpjdyer** [comment]
Fixed with a note on arbitrator.rst.
